*** Comments ***
Object Repository for Login Screen

*** Variables ***
${titleLoginType}           //h1[contains(.,"Log in with")]
${titleLoginPage}           //h1[contains(.,"Log in to your account")]
${txtBxUserName}            //input[@id="inputUsername"]
${txtBxPassword}            //input[@id="inputPassword"]
${btnLogin}                 //button[contains(.,"Log in")]
${titleOverview}            //span[contains(.,"Overview")]

